# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "blockly-terminal"
primary_region = "syd"

[http_service]
  internal_port = 4173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
